apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hub
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tcpdump.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
spec:
  selector:
    app: {{ .Release.Name }}-hub
  ports:
    - name: http
      port: {{ .Values.hub.service.port }}
      targetPort: 8080
      protocol: TCP
